---
title: Brooksbecton.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
name: Brooks Becton
description: Div Slinger in Starkville, MS
avatar: https://raw.githubusercontent.com/brooksbecton/brooksbecton.github.io/master/images/logo.png
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: brooksbecton
  instagram: 
  linkedin: brooksbecton
  pinterest: 
  rss: 
  twitter: YaBoiBrooks
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: 
google_analytics: UA-64267514-2
url: 
baseurl: 
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: compressed
plugins:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
